### ISSUE TITLE
mod_page speed is not installed in the server

### ISSUE THREAD

**Issue by Serversupportstaff** [pagespeed/cpanel#23]
Hi,

I have installed mod_pagespeed in one of my servers. I followed the doc "https://github.com/pagespeed/cpanel" and ended up in the following error.
-----------------------------------------------------
!! Starting mod_pagespeed installation !!
Unable to copy the mod_pagespeed.so to module dir at ./speed-install line 71.
-----------------------------------------------------
I searched on google for the error, tried several solutions nothing helped.
Does anyone know the exact reason and a way to resolve the issue?

Any help will be appreciated.

Thanks in advance.

**Comment by Prajithp** [comment]
can you please provide the following commands output? so that I can try to replicate the same here.

$> uname -i
$> httpd -v
$> which cpio
$> which rpm2cpio

Also try to download the following modspeed rpm from google repo  and paste the result here.

wget  https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_x86_64.rpm
